# -*- coding: utf-8 -*-
"""Q1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZTblExSeidPFn9nSVzMHm_MCdHRBZht
"""

from google.colab import drive

drive.mount('/content/gdrive')

save_path = "/content/gdrive/MyDrive/XML Qns/"

file = "XML_test_flat.xlsx"

import csv


df = pd.read_excel(save_path + file, sheet_name=['Output_Values', 'Output_XML_Path'])

print(df)

print(df['Output_Values']['Counterparty 1'])

test = df['Output_Values']['Counterparty 1']

data = []

for row in test:
  data.append(row)


def convert(row):
  return """<CtrPtySpcfcData>
  <CtrPty></CtrPty>
  <RptgCtrPty>
  <Id>
  <Lgl>
  <Id>
  <LEI>%s</LEI>
  </Id></Lgl></Id></RptgCtrPty></CtrPty>
  <CtrPtySpcfcData>""" % (row[0])

convert(test)

