# -*- coding: utf-8 -*-
"""Q2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vtLNpvh2o_46zEYnIZ4dksExb8B082Md
"""

from google.colab import drive
drive.mount('/content/gdrive')

#input save path of drive folder here:
save_path = "/content/gdrive/MyDrive/XML Qns/"

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import cv2
import zipfile
import json

import csv
import xml.etree.ElementTree as ET

def xml_to_csv(file_path, csv_name) -> None:
  tree = ET.parse(file_path)
  root = tree.getroot()

  with open(csv_name, 'w') as csv_file:
    writer = csv.writer(csv_file)
    headers = (child.tag for child in root[0])
    writer.writerow(headers)
    num_records = len(root)

    for record in range(num_records):
      rec = (child.text for child in root[record])
      writer.writerow(rec)

xml_to_csv(save_path + 'FX_MAS_NEWT_OTHR.xml', save_path + 'yes.csv')

if __name__ == '__main__':
  import sys
  import pathlib

  try:
    file_path = sys.argv[1]
    csv_name = sys.argv[2]
  except IndexError:
    sys.exit('Tow arguments required. One xml path and one save file name.')

with pathlib.Path(file_path) as xml_file:
  if xml_file.is_file():
    xml_to_csv(file_path, csv_name)

  else:
    sys.exit(f'Did not find {file_path}')

import pandas as pd
import xml.etree.ElementTree as ET
tree = ET.parse(save_path + 'FX_MAS_NEWT_OTHR.xml')
root = tree.getroot()

# Extract the data from XML and flatten it into a dictionary
data = []
for CtrPtySpcfcData in root.findall('CtrPtySpcfcData'):
    CtrPtySpcfcData_data = {
        'LEI': CtrPtySpcfcData.find('LEI').text
    }
    data.append(CtrPtySpcfcData_data)
df = pd.DataFrame.from_records(data)
df.to_csv(save_path + 'FX_MAS_NEWT_OTHR_output.csv', index=False)