# -*- coding: utf-8 -*-
"""Q3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2OPG_piaeL36m-GZN9Ejqyv97DaS6fi
"""

from google.colab import drive

drive.mount('/content/gdrive')

save_path = "/content/gdrive/MyDrive/XML Qns/"

!pip install selenium
from selenium import webdriver
!apt-get install chromium-driver

import pandas as pd
import datetime
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

def web_driver():
  options = webdriver.ChromeOptions()
  options.add_argument("--verbose")
  options.add_argument("--no-sandbox")
  options.add_argument("--headless")
  options.add_argument("--disable-gpu")
  options.add_argument("--window-soze = 1920, 1200")
  options.add_argument("--disable-dev-shm-usage")
  driver = webdriver.Chrome(options = options)
  return driver

driver = web_driver()

url = "https://www.ccilindia.com/web/ccil/security-wise-repo-market-summary"

# Open the webpage
driver.get(url)

# Wait for the page to load
time.sleep(5)

df = pd.DataFrame()

i = 0
# Locate the table
while (i < 80):
  table = driver.find_elements(By.XPATH, '//*[@id="securityWiseRepoTable"]/tbody')
  for value in table:
      newline_split = value.text.splitlines()
      for row in newline_split:
        x = row.split()
        #print(x)
        if len(x) != 14:
          continue
        new_x = [x[0], x[1], x[2] + " " + x[3] + " " + x[4], x[5], x[6], x[7], x[8], x[9], x[10], x[11], x[12], x[13]]
        print(new_x)
        df = pd.concat([df, pd.DataFrame([new_x])],axis=0, ignore_index=True)

  # get element
  next= driver.find_element(By.XPATH, '//*[@id="securityWiseRepoTable_next"]')
  # create action chain object
  action = ActionChains(driver)
  # click the item
  action.click(on_element = next)
  # perform the operation
  action.perform()

  i += 1

df.columns= ['Date', 'ISIN', 'Security Deposition', 'Maturity Date', 'Trades', 'Volume (Cr)', 'Open Yield', 'High Yield', 'Low Yield', 'Last Yield', 'Wtd Avg Yield', 'Wtd Avg Price']
# Close the WebDriver
driver.quit()

print(df)

df.to_csv(save_path + 'Security_Wise_Holdings.csv', index=False)